name: Delete skipped docker-feature runs
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      delete_run_by_conclusion_patter:
        default: "skipped"
        type: choice
        options:
          - "skipped"
      delete_workflow_pattern:
        default: "docker-fork.yml"
        type: choice
        options:
          - "docker-fork.yml"

  
jobs:
  del_runs:
    runs-on: ubuntu-22.04
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: "docker-fork.yml"
          delete_run_by_conclusion_patter: "skipped"
