name: Build and publish image from fork
on:
  pull_request:
    types: edited

jobs:
  publish:
    if: ${{github.event.pull_request.head.repo.fork == true}} && ${{github.event.pull_request.base.ref == 'master' || github.evetn.pull_request.base.ref == 'main'}} && ${{github.event.comment.author_association == 'MEMBER'}} && ${{startsWith(github.event.comment.body, '/build')}}
    name: Publish images
    runs-on: ubuntu-22.04
    steps:
      - name: ECHO
        run: |
          echo "github.event pull_request.head.repo.fork ${{github.event.pull_request.head.repo.fork == true}}"
          echo "github.event pull_request.base.ref ${{github.event.pull_request.base.ref}}"
          echo "github.event comment.author_association ${{github.event.comment.author_association}}"
          echo "startsWith(github.event comment.body, '/build')} ${{startsWith(github.event.comment.body, '/build')}}"
