name: Build and publish image from fork
on:
  issue_comment:
    types: created

jobs:
  publish:
    name: Publish images
    if: ${{github.event.issue.pull_request != null && startsWith(github.event.comment.body, '/build') && github.event.comment.author_association == 'MEMBER'}} 
    runs-on: ubuntu-22.04
    steps:
      - name: ECHO
        run: |
          echo "github.event.issue.pull_request != null ${{github.event.issue.pull_request != null}}"
          echo "github.event.comment.author_association ${{github.event.comment.author_association}}"
          echo "startsWith(github.event.comment.body, '/builds') ${{ startsWith(github.event.comment.body, '/build') }}"
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - name: Set latest commit status as pending
        if: ${{contains(fromJSON('["master", "main"]'), steps.comment-branch.outputs.head_ref)}} ||\ 
            ${{startsWith(steps.comment-branch.outputs.head_ref, 'feature/')}} ||\ 
            ${{startsWith(steps.comment-branch.outputs.head_ref, 'hotfix/')}}
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
