name: Build and publish image from fork
on:
  pull_request:
    types: edited

jobs:
  publish:
    name: Publish images
    runs-on: ubuntu-22.04
    steps:
      - name: ECHO
        run: |
          echo "github.event pull_request.head.repo.fork ${{github.event.pull_request.head.repo.fork == true}}"
          echo "github.event pull_request.base.ref ${{github.event.pull_request.base.ref}}"
          echo "github.event pull_request.comments ${{toJSON(github.event.pull_request.comments)}}"